in_mask: '../fetal_data/sub-{subject}/masks/sub-{subject}_task-{task}_bold_mask.nii.gz'
in_bold: '../fetal_data/sub-{subject}/func/sub-{subject}_task-{task}_bold.nii.gz'

in_bold_train: '../fetal_data/sub-{subject,S6|S7|S9}/func/sub-{subject}_task-{task}_bold.nii.gz'
in_bold_test: '../fetal_data/sub-{subject,S1|S3|S10}/func/sub-{subject}_task-{task}_bold.nii.gz'


unettask: Task102_fetal_brain_bold_trainS5to9 #must be Task###_name where ### is >= 100
trainer: nnUNetTrainerV2
architecture: 3d_fullres
checkpoint: model_best

nnunet_env:
  nnUNet_raw_data_base: 'raw_data'
  nnUNet_preprocessed: 'preprocessed'
  RESULTS_FOLDER: 'trained_models'

nnunet_env_tmp:
  nnUNet_raw_data_base: 'raw_data'
  nnUNet_preprocessed: '$SLURM_TMPDIR/preprocessed'
  RESULTS_FOLDER: 'trained_models'


