in_mask: '../fetal_data/sub-{subject}/masks/sub-{subject}_task-{task}_bold_mask.nii.gz'
in_bold: '../fetal_data/sub-{subject}/func/sub-{subject}_task-{task}_bold.nii.gz'

in_bold_train: '../fetal_data/sub-{subject,S[3]}/func/sub-{subject}_task-{task}_bold.nii.gz'
in_bold_test: '../fetal_data/sub-{subject,S1|S3|S10}/func/sub-{subject}_task-{task}_bold.nii.gz'



subjects:
 - S1
 - S3
 - S5
 - S6
 - S7
 - S8
 - S9
 - S10

tasks:
 - singing1
 - singing2
 - rest

unettask: Task101_fetal_brain_bold #must be Task###_name where ### is >= 100
trainer: nnUNetTrainerV2
architecture: 3d_fullres
checkpoint: model_best

nnunet_env:
  nnUNet_raw_data_base: 'raw_data'
  nnUNet_preprocessed: 'preprocessed'
  RESULTS_FOLDER: 'trained_models'

nnunet_env_tmp:
  nnUNet_raw_data_base: 'raw_data'
  nnUNet_preprocessed: '$TMPDIR/preprocessed'
  RESULTS_FOLDER: 'trained_models'


#--- extra below:

ants:
  dim: 3
  random_seed: 42
  intensity_opts: '-u 1 -w [0.01,0.99] -z 1'
  linear:
      reg_iterations: '1000x500x250x0'
      shrink_factors: '6x4x2x1'
      smoothing_factors: '4x2x1x0'
  deform:
      shrink_factors: '12x6x4x2x1'  # default in antsMVTC2: 6x4x2x1
      smoothing_factors: '6x3x2x1x0vox' # default in antsMVTC2: 3x2x1x0
      reg_iterations: '100x100x70x50x10' # default in antsMVTC2: 100x100x70x20
      transform_model: 'SyN[0.1,3,0]'
      sim_metric: CC
  shape_update:
      gradient_step: 0.25
